spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB:shopdb}
    username: ${POSTGRES_USER:shop}
    password: ${POSTGRES_PASSWORD:secret}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
            scope: openid,profile,email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
server:
  port: 8080
app:
  security:
    jwtSecret: ${JWT_SECRET:change-me-dev-secret}
